name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  lint:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dev dependencies
        run: poetry install

      - name: Lint with Flake8
        run: poetry run flake8 dbt_llm_tools tests client

      - name: Lint with pylint
        run: poetry run pylint dbt_llm_tools tests client

      - name: Test with pytest
        run: poetry run pytest tests
